### ISSUE TITLE
Many profiles use versions/inScheme improperly

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-authored-profiles#35]
Every profile must have an ID, and every profile must have one or more versions. Every version must have an ID that is different from all other versions and from the overall profile ID. Every concept, statement template, and pattern must be `inScheme` of the current version, not of the overall profile ID (that is already known, because `concepts`, `templates`, and `patterns` denote inverse sub properties of `skos:inScheme`).

Most profiles in the repository fail to follow one or more of the rules above.

**Comment by jhaag75** [comment]
Can you submit some PRs to address these? I'm guessing a majority of them are referenced incorrectly from the statement templates and patterns. Thought we would have caught that awhile back. I'll try to dig in and take a look later this week unless you know exactly which ones to address already.

**Comment by FlorianTolk** [comment]
Sorry it took so long to fix these errors, but I believe everything is in order now, please let me know if you find any issues with this pull request!

**Comment by jhaag75** [comment]
Only the inScheme IRI should be updated to use the latest version. Not the overall id of the concepts.

**Comment by FlorianTolk** [comment]
Some of the overall `id` fields included versioning information. The only changes I made to the overall `id` fields was to remove the version number from them like I did in activity-streams.json

If there is an important reason to undo these changes, I can make that happen as well. :-)

**Comment by jhaag75** [comment]
The concepts should not have versioning in the IRI. For example, in acrossx.jsonld:

https://w3id.org/xapi/acrossx/v1.1/activities/message

Concepts such as verbs, activity types, extensions should not ever change the IRI. The only thing that gets versioned is the profile itself, in the "versions" section and then each concept's inScheme property is updated to reference the profile version it's associated with. The updates you made for inScheme are fine. It's the concepts that should not have any versioning info in their IRI. Thanks Florian!
