### ISSUE TITLE
prefLabel, definition Reversed in Starter Template

### ISSUE THREAD

**Issue by oconnetf** [adlnet/xapi-authored-profiles#36]
Looks to me like prefLabel should be the "title" of the verb and that definition should prompt a description per [the examples in the spec](https://github.com/adlnet/xapi-profiles/blob/master/xapi-profiles-structure.md#examples-1).

**Comment by fugu13** [comment]
Yup, that definitely needs to be changed, looks like the Verb and Activity Type concepts got messed up

**Comment by jhaag75** [comment]
Thanks for catching this typo! Updated so closing this issue. https://github.com/adlnet/xapi-authored-profiles/pull/38
