### ISSUE TITLE
DOD ISD Profile

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-authored-profiles#48]
@oconnetf @CAEUSAISG 

You might want to pull down a copy from the master. I updated the versioning numbers to match semantic versioning (per these guidelines: http://xapi.vocab.pub/resources/index.html). 

The JSON doc has several validation errors. Before I can import this into xapi.vocab.pub can you fix the JSON? You can use JSON Lint or some other JSON formatter.

**Comment by oconnetf** [comment]
Thanks, @jhaag75. Didn't think to re-lint it after adding multi-line definition entries.

Speaking of which, I wonder if we should add clarity to the examples in the templates? I think in a copy/paste way, those examples might include invalid JSON.

**Comment by jhaag75** [comment]
The examples should be valid. It's special characters in your profile that
aren't validating, I think.
