### ISSUE TITLE
invalid JSON

### ISSUE THREAD

**Issue by garajo** [adlnet/xapi-authored-profiles#53]
Looks like a recent change invalidated JSON format for the `'acrossx` profile. I tried to fix it, except it has been updated and I couldn't work it out. JSON linting resulted in the following message.

![screenshot from 2018-03-19 11-19-35](https://user-images.githubusercontent.com/2825366/37614247-7e3350ae-2b67-11e8-9001-e5b6891e79c3.png)

https://github.com/adlnet/xapi-authored-profiles/blob/master/acrossx/acrossx.jsonld#L41-L59

**Comment by FlorianTolk** [comment]
Thanks for bringing this up! I will look at previous versions and fix that!

**Comment by FlorianTolk** [comment]
Pull Request [#54](https://github.com/adlnet/xapi-authored-profiles/pull/54) should fix it

**Comment by garajo** [comment]
Happy to help. Thanks for the fix.
