### ISSUE TITLE
Starter Template Error at line 56

### ISSUE THREAD

**Issue by DataBeeGood** [adlnet/xapi-authored-profiles#67]
JSON Lint (https://jsonlint.com/)  for your starter template notes a problem at line 56.
I am trying to understand profiles 
so I am wondering if the square bracket is misplaced 
and the flow should be simply a curly close-comma-curly open  },{  
which continues "concepts" 
and then closing the square bracket for "concepts" just prior to "templates"

Thanks for your assistance!

-------------------------------------------------------------------------
Error: Parse error on line 56:
...chema": ""		}	],	{		"id": "https://w
--------------------^
Expecting 'STRING', got '{'

----------------------------------------

**Comment by jhaag75** [comment]
Thank you. This has been merged.

**Comment by DataBeeGood** [comment]
Most welcome.
