### ISSUE TITLE
Played and Initialized in the Video Profile

### ISSUE THREAD

**Issue by Dustin-Walker** [adlnet/xapi-authored-profiles#70]
While working with a client, we ran into a bit of confusion around the 'played' and 'initialized' verbs in the xAPI Video Profile.

The played verb in the profile states:
```
{
      "id": "https://w3id.org/xapi/video/verbs/played",
      "inScheme": "https://w3id.org/xapi/video/v1.0.2",
      "type": "Verb",
      "exactMatch": [ {
        "id": "http://activitystrea.ms/schema/1.0/play"
      } ],
      "definition": {
        "en": "Indicates that the actor started experiencing the recorded media object."
      },
      "prefLabel": {
        "en": "played"
      }
    }
```

The initialized verb states:
```
{
      "id": "https://w3id.org/xapi/video/templates#initialized",
      "inScheme": "https://w3id.org/xapi/video/v1.0.2",
      "prefLabel": {
        "en": "Initialized"
      },
      "definition": {
        "en": "The statement template and rules associated with a video being initialized or started."
      },
      "verb": "http://adlnet.gov/expapi/verbs/initialized",
...
```

We typically use the `initialized` for the first time when a user starts a video and the `played` verb when the user resumes a video. But this profile seems to state that both verbs are for when the video starts.

Can somebody provide some clarification on this? Which verb should be used for the very first time somebody starts a video?

Thank you!

**Comment by jhaag75** [comment]
Hi @Dustin-Walker. 

The code examples you provided are for two different things. One is the verb "played" and the other is the "initialized" template. However, there are both "initialized" and "played" verbs in the video profile. The initialized verb is used when the the video is initialzed. And the played verb is used when the play button is pushed.

Hope this helps! Also, check out this documentation for more insight: https://liveaspankaj.gitbooks.io/xapi-video-profile/content/

Let me @jhaag75 or @liveaspankaj  know if we can be of any help! We are part of the group that built the video profile.

Regards,

J Haag
