### ISSUE TITLE
Video Profile 1.0.3

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-authored-profiles#77]
Just noticed the latest version of the video profile hasn't been imported into xapi.vocab.pub.

https://github.com/adlnet/xapi-authored-profiles/tree/master/video/v1.0.3

This is a request to import the RDF .ttl file so the latest version will show up at xapi.vocab.pub. Thanks.

**Comment by jhaag75** [comment]
@FlorianTolk @andyjohnson @adl-trey Any updates on this issue?

**Comment by FlorianTolk** [comment]
I believe I updated it to version 1.0.3

**Comment by jhaag75** [comment]
Ok thanks! xapi.vocab.pub appears to be down again.

**Comment by jhaag75** [comment]
1.0.3 is still not appearing on xapi.vocab.pub so I don't believe it was imported yet.

**Comment by FlorianTolk** [comment]
I just ran the import again, and it looks like it succeeded.
![image](https://user-images.githubusercontent.com/33456535/65450271-bfc66400-de0a-11e9-8adb-cc7ccc3e4f4f.png)

**Comment by jhaag75** [comment]
Thanks Florian.
