### ISSUE TITLE
JSON breaking with trailing comma in Open Badges and Activity Streams profile updates

### ISSUE THREAD

**Issue by mpkliewer** [adlnet/xapi-authored-profiles#81]
There's a trailing comma that breaks the JSON in the `versions` property (`generatedAtTime`) in the recent **Open Badges** and **Activity Streams** profile updates:

### Open Badges
https://github.com/adlnet/xapi-authored-profiles/commit/df078fd776eaa1c5d78739a72c82b13399ddff1d#diff-7189be34380d3455d86180af12c8c629R20

### Activity Streams
https://github.com/adlnet/xapi-authored-profiles/commit/df078fd776eaa1c5d78739a72c82b13399ddff1d#diff-55e0889e53bc346f249a18c5d4f53ec6R20

Thanks!

**Comment by vbhayden** [comment]
Corrected with https://github.com/adlnet/xapi-authored-profiles/pull/83
