### ISSUE TITLE
JSON breaking with extra curly bracket in Video Profile v1.0.2 update

### ISSUE THREAD

**Issue by mpkliewer** [adlnet/xapi-authored-profiles#82]
There's an extra curly bracket that remains after the `exactMatch` property of the "paused" verb was updated to an array of ID strings:

https://github.com/adlnet/xapi-authored-profiles/commit/df078fd776eaa1c5d78739a72c82b13399ddff1d#diff-8259c7e68b8d556cf515280bd4f32677R28

Thanks!

**Comment by vbhayden** [comment]
Corrected with https://github.com/adlnet/xapi-authored-profiles/pull/83
