### ISSUE TITLE
Invalid Timestamps

### ISSUE THREAD

**Issue by cliffcaseyyet** [adlnet/xapi-authored-profiles#89]
Hello,

While testing a new automated xAPI Profile validator, we noticed that there was a potential conformance issue in a profile in this repo.

Specifically, a timestamp format in **adb/adb.jsonld** on line 20

    "versions": [
     {
      "id": "https://w3id.org/xapi/adb/v1.0",
      "generatedAtTime": "2017-06-30T8:26:00Z",
      "wasRevisionOf": ["https://w3id.org/xapi/adb"]
     }

According to spec, the "generatedAtTime" property should have an iso-8601 format timestamp, which needs a zero-padded hour between 00 and 24. 

There was another an issue where the same property did not follow Timestamp syntax in:

dod-isd/dod-isd.jsonld | line 16 

We wanted to share in case you were unaware of the issue.

Thanks,
Cliff Casey

**Comment by FlorianTolk** [comment]
Corrected with [this merge](https://github.com/adlnet/xapi-authored-profiles/commit/04566db72b5b48e8e163365848289f293b108a1f)
