### ISSUE TITLE
Change management is very hard with many unrelated profiles

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-authored-profiles#9]
Managing releases, making sure people coming to the repo are looking at the right versions of profiles, and managing contributions are all made more difficult by having all these profiles in one repo. Keeping each profile in its own repository would be a substantial improvement with no real downsides.

**Comment by jhaag75** [comment]
I think having each in it's own repo is a good idea. We need to get a formal process documented. I don't see anything preventing this and would be a good practice going forward.
